version: 2

env:
  - CGO_ENABLED=0

builds:
  - id: minio
    main: .
    binary: minio
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
    flags:
      - -tags=kqueue
      - -trimpath
    ldflags:
      - "{{ .Env.LDFLAGS }}"

archives:
  - id: minio
    ids:
      - minio
    name_template: "minio_{{ .Env.PKG_VERSION }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "minio_{{ .Env.PKG_VERSION }}_checksums.txt"
  algorithm: sha256

release:
  github:
    owner: pgsty
    name: minio
  draft: true
  prerelease: false
  mode: append
  replace_existing_artifacts: false
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "Merge pull request"
      - "Merge branch"

announce:
  skip: true
